name: Fabricate
on:
  workflow_call:
    inputs:
      board:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      board:
        description: project to create docs for
        required: true
        type: choice
        options:
        - amoeba
        - panel

jobs:
  generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.board }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create PCBA and position folders with write access
        run: |
          mkdir pcba
          ls -la 

      - name: KiBot
        uses: INTI-CMNB/KiBot@v2_k6
        with:
          config: ./bin/fab.kibot.yaml
          schema: ./${{ inputs.board }}/${{ inputs.board }}.kicad_sch
          board: ./${{ inputs.board }}/${{ inputs.board }}.kicad_pcb
          dir: ./${{ inputs.board }}
          verbose: 1

      #- name: Zip position files with readme, if using PCBWay as panel
      #  run: |
      #    zip --junk-paths pcba/position_files.zip \
      #       position/*.csv  doc/README_pcba_pcbway.md
      #    ls -la . pcba

      - name: Upload Gerber zip, BOM, position 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.board }}-gerber-and-pcba
          path: |
            ./${{ inputs.board }}/${{ inputs.board }}-gerbers.zip
            ./${{ inputs.board }}/pcba/*

      ####
      # Logs
      - name: Debug list directory
        if: ${{ always() }}
        run: |
          pwd
          ls -lA . gerber pcba
        
      - name: Upload Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.board }}_logs_fab
          path: |
            ./${{ inputs.board }}/*.log
            ./${{ inputs.board }}/*.txt

